---
pipelines:
  adp:
    processes:
    - name: adpst
      host: nrt
      resource: adpst.resource
    - name: adpmon
      host: nrt
      resource: adpmon.resource
    - name: adp
      host: nrt
      resource: adp.resource
    - name: adpfin
      host: nrt
      resource: adpfin.resource
    - name: cleanopus
      host: nrt
      resource: cleanopus.resource
    - name: cleanosf
      host: nrt
      resource: cleanosf.resource
  nrtinput:
    processes:
    - name: ninpst
      host: nrt
      resource: ninpst.resource
    - name: ninput
      host: nrt
      resource: ninput.resource
    - name: ninpmd
      host: nrt
      resource: ninpmd.resource
    - name: ninpmp
      host: nrt
      resource: ninpmp.resource
    - name: ninpmc
      host: nrt
      resource: ninpmc.resource
    - name: ninpfi
      host: nrt
      resource: ninpfi.resource
    - name: cleanopus
      host: nrt
      resource: cleanopus.resource
    - name: cleanosf
      host: nrt
      resource: cleanosf.resource
---
comments:
	This document is in YAML format so keep to the exact structure
	as above when adding new configuration data.
